"""changed contact_email to phone

Revision ID: 1720229431
Revises: 
Create Date: 2024-07-06 01:30:31.209800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1720229431'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('phone', sa.String(length=100), nullable=False))
    op.drop_column('profile', 'contact_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('profile', 'phone')
    # ### end Alembic commands ###
