"""experience row name change

Revision ID: 1720230127
Revises: 1720229431
Create Date: 2024-07-06 01:42:07.803447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1720230127'
down_revision: Union[str, None] = '1720229431'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_experience_author_id_user', 'experience', type_='foreignkey')
    op.create_foreign_key(op.f('fk_experience_user_id_user'), 'experience', 'user', ['user_id'], ['id'])
    op.drop_column('experience', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_experience_user_id_user'), 'experience', type_='foreignkey')
    op.create_foreign_key('fk_experience_author_id_user', 'experience', 'user', ['author_id'], ['id'])
    op.drop_column('experience', 'user_id')
    # ### end Alembic commands ###
